name: Selenium Web Automation Tests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-allure

      - name: Run tests
        run: |
          pytest --alluredir=reports/allure_reports TestSuite.py

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: reports/allure_reports

      - name: Upload test logs
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: reports/TestLogs.log

      - name: Generate Allure report history
        run: |
          allure generate reports/allure_reports -o allure-history --clean

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
